export const clinics = [
  {
    id: 1,
    name: "Acıbadem Maslak Hastanesi",
    category: "Genel Hastane",
    city: "İstanbul",
    district: "Maslak",
    specialties: ["Kalp Cerrahisi", "Onkoloji", "Estetik"],
    rating: 4.8,
    reviewCount: 1250,
    priceRange: "$$",
    image: "/clinics/acibadem.jpg",
    description: "Uluslararası standartlarda sağlık hizmeti...",
    accreditations: ["JCI", "ISO 9001"],
    languages: ["Türkçe", "İngilizce", "Arapça"],
    services: [
      { name: "Kalp Ameliyatı", priceRange: "15.000€ - 25.000€" },
      { name: "Estetik Rinoplasti", priceRange: "3.000€ - 5.000€" },
    ],
    phone: "+905551112233",
    whatsapp: "+905551112233",
  },

  {
    id: 2,
    name: "Medicana Ankara Hastanesi",
    category: "Genel Hastane",
    city: "Ankara",
    district: "Çankaya",
    specialties: ["Nöroloji", "Ortopedi", "Göz"],
    rating: 4.6,
    reviewCount: 980,
    priceRange: "$$",
    image: "/clinics/medicana.jpg",
    description: "Modern teknolojilerle donatılmış hastane...",
    accreditations: ["ISO 9001"],
    languages: ["Türkçe", "İngilizce"],
    services: [
      { name: "Beyin Cerrahisi", priceRange: "10.000€ - 20.000€" },
      { name: "Katarakt Ameliyatı", priceRange: "1.500€ - 3.000€" },
    ],
    phone: "+905556667788",
    whatsapp: "+905556667788",
  },

  {
    id: 3,
    name: "DentGroup İstanbul",
    category: "Diş",
    city: "İstanbul",
    district: "Kadıköy",
    specialties: ["Diş Estetiği", "İmplant"],
    rating: 4.9,
    reviewCount: 1500,
    priceRange: "$",
    image: "/clinics/dentgroup.jpg",
    description: "Türkiye'nin lider diş kliniklerinden biri.",
    accreditations: ["JCI"],
    languages: ["Türkçe", "İngilizce", "Almanca"],
    services: [
      { name: "Diş İmplantı", priceRange: "1.000€ - 2.500€" },
      { name: "Zirkonyum Kaplama", priceRange: "500€ - 1.200€" },
    ],
    phone: "+905553334455",
    whatsapp: "+905553334455",
  },

  {
    id: 4,
    name: "Estetik International Antalya",
    category: "Estetik",
    city: "Antalya",
    district: "Muratpaşa",
    specialties: ["Estetik Cerrahi", "Medikal Estetik"],
    rating: 4.7,
    reviewCount: 1120,
    priceRange: "$$$",
    image: "/clinics/estetik_international.jpg",
    description: "Uluslararası estetik cerrahi uzmanlarıyla hizmetinizde.",
    accreditations: ["JCI", "ISO 14001"],
    languages: ["Türkçe", "İngilizce", "Fransızca"],
    services: [
      { name: "Liposuction", priceRange: "3.000€ - 6.000€" },
      { name: "Botoks", priceRange: "300€ - 700€" },
    ],
    phone: "+905558889900",
    whatsapp: "+905558889900",
  },

  {
    id: 5,
    name: "Ankara Göz Merkezi",
    category: "Göz",
    city: "Ankara",
    district: "Yenimahalle",
    specialties: ["Lazer Cerrahisi", "Katarakt", "Glokom"],
    rating: 4.5,
    reviewCount: 840,
    priceRange: "$$",
    image: "/clinics/ankara_goz.jpg",
    description: "Göz hastalıklarında öncü merkez.",
    accreditations: ["ISO 9001"],
    languages: ["Türkçe", "İngilizce"],
    services: [
      { name: "Lazer Tedavisi", priceRange: "1.200€ - 2.500€" },
      { name: "Katarakt Ameliyatı", priceRange: "1.500€ - 3.000€" },
    ],
    phone: "+905559991122",
    whatsapp: "+905559991122",
  },

  {
    id: 6,
    name: "Saç Ekim Merkezi İzmir",
    category: "Saç Ekimi",
    city: "İzmir",
    district: "Konak",
    specialties: ["FUE", "DHI", "PRP Tedavisi"],
    rating: 4.8,
    reviewCount: 1150,
    priceRange: "$$",
    image: "/clinics/sac_ekim_izmir.jpg",
    description: "Saç ekimi ve restorasyonda uzman klinik.",
    accreditations: ["JCI"],
    languages: ["Türkçe", "İngilizce"],
    services: [
      { name: "FUE Saç Ekimi", priceRange: "2.000€ - 4.000€" },
      { name: "PRP Tedavisi", priceRange: "500€ - 1.000€" },
    ],
    phone: "+905550011223",
    whatsapp: "+905550011223",
  },

  {
    id: 7,
    name: "Medipol Üniversitesi Hastanesi",
    category: "Genel Hastane",
    city: "İstanbul",
    district: "Bağcılar",
    specialties: ["Kardiyoloji", "Ortopedi", "Nefroloji"],
    rating: 4.4,
    reviewCount: 990,
    priceRange: "$$",
    image: "/clinics/medipol.jpg",
    description: "Eğitim ve araştırma odaklı üniversite hastanesi.",
    accreditations: ["JCI", "ISO 9001"],
    languages: ["Türkçe", "İngilizce"],
    services: [
      { name: "Kalp Muayenesi", priceRange: "100€ - 300€" },
      { name: "Diz Protezi", priceRange: "8.000€ - 15.000€" },
    ],
    phone: "+905554433221",
    whatsapp: "+905554433221",
  },

  {
    id: 8,
    name: "Dental Park Antalya",
    category: "Diş",
    city: "Antalya",
    district: "Alanya",
    specialties: ["Diş Estetiği", "Ortodonti"],
    rating: 4.7,
    reviewCount: 770,
    priceRange: "$",
    image: "/clinics/dental_park.jpg",
    description: "Antalya'nın önde gelen diş kliniklerinden.",
    accreditations: ["ISO 9001"],
    languages: ["Türkçe", "İngilizce", "Rusça"],
    services: [
      { name: "Diş Beyazlatma", priceRange: "200€ - 500€" },
      { name: "Ortodonti Tedavisi", priceRange: "1.000€ - 3.000€" },
    ],
    phone: "+905559988776",
    whatsapp: "+905559988776",
  },

  {
    id: 9,
    name: "Estetik Klinik İzmir",
    category: "Estetik",
    city: "İzmir",
    district: "Bornova",
    specialties: ["Estetik Cerrahi", "Medikal Estetik"],
    rating: 4.6,
    reviewCount: 830,
    priceRange: "$$",
    image: "/clinics/estetik_izmir.jpg",
    description: "Modern tekniklerle estetik çözümler sunar.",
    accreditations: ["JCI"],
    languages: ["Türkçe", "İngilizce"],
    services: [
      { name: "Burun Estetiği", priceRange: "3.000€ - 6.000€" },
      { name: "Dolgu", priceRange: "400€ - 800€" },
    ],
    phone: "+905552223344",
    whatsapp: "+905552223344",
  },

  {
    id: 10,
    name: "Ortopedi Merkezi Ankara",
    category: "Ortopedi",
    city: "Ankara",
    district: "Keçiören",
    specialties: ["Diz Protezi", "Omuz Cerrahisi"],
    rating: 4.3,
    reviewCount: 690,
    priceRange: "$$",
    image: "/clinics/ortopedi_ankara.jpg",
    description: "Ortopedi alanında uzman kadro ile hizmet verir.",
    accreditations: ["ISO 9001"],
    languages: ["Türkçe", "İngilizce"],
    services: [
      { name: "Diz Protezi", priceRange: "10.000€ - 18.000€" },
      { name: "Omuz Ameliyatı", priceRange: "8.000€ - 15.000€" },
    ],
    phone: "+905557771234",
    whatsapp: "+905557771234",
  },

  {
    id: 11,
    name: "Sağlık Park Hastanesi",
    category: "Genel Hastane",
    city: "İstanbul",
    district: "Şişli",
    specialties: ["Onkoloji", "Nöroloji"],
    rating: 4.5,
    reviewCount: 1020,
    priceRange: "$$",
    image: "/clinics/saglik_park.jpg",
    description: "Modern tıp teknolojileriyle kaliteli sağlık.",
    accreditations: ["JCI", "ISO 9001"],
    languages: ["Türkçe", "İngilizce", "Fransızca"],
    services: [
      { name: "Kemoterapi", priceRange: "12.000€ - 22.000€" },
      { name: "Beyin MR", priceRange: "500€ - 1.000€" },
    ],
    phone: "+905559963258",
    whatsapp: "+905559963258",
  },

  {
    id: 12,
    name: "İzmir Göz Merkezi",
    category: "Göz",
    city: "İzmir",
    district: "Karşıyaka",
    specialties: ["Katarakt", "Lazer Cerrahisi"],
    rating: 4.6,
    reviewCount: 720,
    priceRange: "$$",
    image: "/clinics/izmir_goz.jpg",
    description: "Göz sağlığında lider merkez.",
    accreditations: ["ISO 9001"],
    languages: ["Türkçe", "İngilizce", "Arapça"],
    services: [
      { name: "Katarakt Ameliyatı", priceRange: "1.500€ - 3.000€" },
      { name: "Lazer Tedavisi", priceRange: "1.200€ - 2.500€" },
    ],
    phone: "+905551234567",
    whatsapp: "+905551234567",
  },

  {
    id: 13,
    name: "Hairmed Saç Ekimi",
    category: "Saç Ekimi",
    city: "Antalya",
    district: "Muratpaşa",
    specialties: ["FUE", "DHI"],
    rating: 4.7,
    reviewCount: 860,
    priceRange: "$$",
    image: "/clinics/hairmed.jpg",
    description: "Deneyimli ekibimizle sağlıklı saçlara kavuşun.",
    accreditations: ["JCI"],
    languages: ["Türkçe", "İngilizce", "Rusça"],
    services: [
      { name: "FUE Saç Ekimi", priceRange: "2.000€ - 4.500€" },
      { name: "DHI Saç Ekimi", priceRange: "2.500€ - 5.000€" },
    ],
    phone: "+905558877665",
    whatsapp: "+905558877665",
  },

  {
    id: 14,
    name: "Medical Park İzmir",
    category: "Genel Hastane",
    city: "İzmir",
    district: "Buca",
    specialties: ["Kardiyoloji", "Ortopedi", "Nöroloji"],
    rating: 4.4,
    reviewCount: 940,
    priceRange: "$$",
    image: "/clinics/medical_park.jpg",
    description: "Hasta memnuniyeti odaklı hizmet.",
    accreditations: ["JCI", "ISO 9001"],
    languages: ["Türkçe", "İngilizce"],
    services: [
      { name: "Kalp Kontrolü", priceRange: "100€ - 350€" },
      { name: "Diz Protezi", priceRange: "8.000€ - 16.000€" },
    ],
    phone: "+905559955443",
    whatsapp: "+905559955443",
  },

  {
    id: 15,
    name: "Gözde Göz Merkezi",
    category: "Göz",
    city: "İstanbul",
    district: "Beşiktaş",
    specialties: ["Lazer Cerrahisi", "Katarakt"],
    rating: 4.7,
    reviewCount: 1200,
    priceRange: "$$",
    image: "/clinics/gozde_goz.jpg",
    description: "Göz sağlığında uzman kadro.",
    accreditations: ["JCI"],
    languages: ["Türkçe", "İngilizce", "Arapça"],
    services: [
      { name: "Lazer Tedavisi", priceRange: "1.200€ - 2.500€" },
      { name: "Katarakt Ameliyatı", priceRange: "1.500€ - 3.000€" },
    ],
    phone: "+905552211334",
    whatsapp: "+905552211334",
  },
];
